const Jobdata = {
    InternshipData: [
    {
      id: "0",
      Title: "Engineer",
      Company: "Qualcomm",
      Location: "Hyderabad",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link: "https://qualcomm.wd5.myworkdayjobs.com/en-US/External/job/Engineer_3041558?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e",
      img_src: require("../../Screens/Job/img/jobLogo/qualcomm.png"),
      alt: "Logo",
    },
    {
      id: "1",
      Title: "Product Manager",
      Company: "Bharat Pe",
      Location: "Gurgaon",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-6",
      WorkType: "Full Time",
      Link: "https://bharatpe.com/career",
      img_src: require("../../Screens/Job/img/jobLogo/bharatpe.png"),
      alt: "Logo",
    },
    {
      id: "2",
      Title: "Engineer/Senior Engineer/Assistant Manager",
      Company: "Azure power",
      Location: "Assam/UP/Rajasthan",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-7",
      WorkType: "Full Time",
      Link:"https://www.azurepower.com/current-openings",
      img_src: require("../../Screens/Job/img/jobLogo/azurepower.png"),
      alt: "Logo",
    },
    {
      id: "3",
      Title: "Multiple Openings",
      Company: "Pinelabs",
      Location: "Pan India",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-6",
      WorkType: "Full Time",
      Link:"https://www.pinelabs.com/careers/open-jobs",
      img_src: require("../../Screens/Job/img/jobLogo/pinelabs.jpg"),
      alt: "Logo",
    },
    {
      id: "4",
      Title: "Multiple Openings",
      Company: "Dodla Dairy",
      Location: "Pan India",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "",
      WorkType: "Full Time",
      Link:"https://www.dodladairy.com/current_openings",
      img_src: require("../../Screens/Job/img/jobLogo/dodla.png"),
      alt: "Logo",
    },


    {
      id: "5",
      Title: "Business Development Manager",
      Company: "ClassPlus",
      Location: "Multiple Cities",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-4",
      WorkType: "Full Time",
      Link:"https://classplusapp.com/careers/job-description?jobId=a615c4a25d3dd8",
      img_src : require("../../Screens/Job/img/jobLogo/classplus.png"),
      alt:"logo"
    },
    {
      id: "6",
      Title: "Admission Counsellor",
      Company: "upGrad",
      Location: "Indiqube, Bengaluru, Karnataka,",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link:"https://upgrad.darwinbox.in/ms/candidate/main/careers/a631ae4672ff39",
      img_src :require("../../Screens/Job/img/jobLogo/upGrad.png"),
      alt:"Logo"
    },
    {
      id: "7",
      Title: "Manager",
      Company: "Paytm",
      Location: "Pan India",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-6",
      WorkType: "Part Time",
      Link:"https://jobs.lever.co/paytm",
      img_src : require("../../Screens/Job/img/jobLogo/paytm.png"),
      alt:"Logo"
    },
    {
      id: "8",
      Title: "Multiple Openings",
      Company: "Ola",
      Location: "",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://ola.skillate.com/",
      img_src : require("../../Screens/Job/img/jobLogo/ola.png"),
      alt:"Logo"
    },
    {
      id: "9",
      Title: "Android developer",
      Company: "Cred",
      Location: "Bengaluru, Karnataka",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://careers.cred.club/jobPosting?apply_url=https://jobs.lever.co/cred/f1b5843c-7a21-4747-8f08-3fa442aa7b9a/apply",
      img_src : require("../../Screens/Job/img/jobLogo/cred.png"),
      alt:"Logo"
    },
    {
      id: "10",
      Title: "Multiple Openings",
      Company: "Expressbees",
      Location: "Chennai,Pune",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-7",
      WorkType: "Full Time",
      Link:"https://www.xpressbees.com/careers",
      img_src : require("../../Screens/Job/img/jobLogo/expressbees.jpg"),
      alt:"Logo"
    },
    {
      id: "11",
      Title: "Senior Data Engineer",
      Company: "CityMall",
      Location: "Gurgaon",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://www.citymall.live/gurgaon/tech/sr-data-engineer",
      img_src : require("../../Screens/Job/img/jobLogo/citymall.png"),
      alt:"Logo"
    },
    {
      id: "12",
      Title: "Customer Success Executive",
      Company: "Groww",
      Location: "",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-1",
      WorkType: "Full Time",
      Link:"https://groww.skillate.com/jobs/43915",
      img_src :require("../../Screens/Job/img/jobLogo/groww.png"),
      alt:"Logo"
    },
    {
      id: "13",
      Title: "Customer Success Executive",
      Company: "Jumbotail",
      Location: "",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "",
      WorkType: "Full Time",
      Link:"https://jumbotail.com/customer-success-executive/",
      img_src :require("../../Screens/Job/img/jobLogo/jumbotail.png"),
      alt:"Logo"
    },
    {
      id: "14",
      Title: "Business & Strategy",
      Company: "Slice",
      Location: "Bengaluru, Karnataka, India",
      Date: "18-07-2022",
      Type: "Non Govt.",
      Experience: "1-4",
      WorkType: "Full Time",
      Link:"https://jobs.smartrecruiters.com/slice1/743999848717567-business-strategy",
      img_src : require("../../Screens/Job/img/jobLogo/slice.png"),
      alt:"Logo"
    },
    {
      id: "15",
      Title: "Junior Video Designer & Editor ",
      Company: "InMobi",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link:"https://www.inmobi.com/company/openings/marketing/jobid/4461075",
      img_src : require("../../Screens/Job/img/jobLogo/inmobi.png"),
      alt:"Logo"
    },
    {
      id: "16",
      Title: "Software Development Engineer - 2",
      Company: "Cashfree",
      Location: "",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "",
      WorkType: "Full Time",
      Link:"https://www.cashfree.com/careers/software-development-engineer-2/",
      img_src : require("../../Screens/Job/img/jobLogo/cashfree.png"),
      alt:"Logo"
    },
    {
      id: "17",
      Title: "Application Developer",
      Company: "Ibm",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-6",
      WorkType: "Full Time",
      Link:"https://careers.ibm.com/job/15917093/application-developer-microsoft-net-ahmedabad-in/?codes=IBM_CareerWebSite",
      img_src : require("../../Screens/Job/img/jobLogo/ibm.png"),
      alt:"Logo"
    },
    {
      id: "18",
      Title: "Executive Business Development",
      Company: "Progcap",
      Location: "Delhi",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://www.progcap.com/open-positions",
      img_src : require("../../Screens/Job/img/jobLogo/progcap.png"),
      alt:"Logo"
    },
    {
      id: "19",
      Title: "Writer - Brand Solutions",
      Company: "Your Story",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-5",
      WorkType: "Full Time",
      Link:"https://yourstory.com/jobs/details/b12d7fd6-ac74-11e9-a2a3-2a2ae2dbcce4",
      img_src : require("../../Screens/Job/img/jobLogo/yourstory.png"),
      alt:"Logo"
    },
    {
      id: "20",
      Title: "Product Support Specialist",
      Company: "Practo",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-2",
      WorkType: "Full Time",
      Link:"https://practo.app.param.ai/jobs/product-support-specialist-810-505",
      img_src : require("../../Screens/Job/img/jobLogo/practo.png"),
      alt:"Logo"
    },
    {
      id: "21",
      Title: "Android Developer",
      Company: "Locus",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://locus.freshteam.com/jobs/NOR4pCVRS-M_/android-developer-1-2-yrs-work-exp",
      img_src : require("../../Screens/Job/img/jobLogo/locus.png"),
      alt:"Logo"
    },
    {
      id: "22",
      Title: "Lead-Hub Operations",
      Company: "Flipkart",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "",
      WorkType: "Full Time",
      Link:"https://www.flipkartcareers.com/#!/job-view/lead-hub-operations-bangalore-karnataka-2022081917210363",
      img_src : require("../../Screens/Job/img/jobLogo/flipkart.jpg"),
      alt:"Logo"
    },
    {
      id: "23",
      Title: "DevOps Engineer",
      Company: "Mobikwik",
      Location: "",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-1",
      WorkType: "Full Time",
      Link:"https://www.mobikwik.com/careers/job_desc?job_category=Technology&role=devops_engineer_1",
      img_src : require("../../Screens/Job/img/jobLogo/mobikwik.png"),
      alt:"Logo"
    },
    {
      id: "24",
      Title: "Scientific Assistant/Medical Social Worker",
      Company: "BARC",
      Location: "Mumbai, GCNEP, Haryana, and RMRC, Kolkata",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://www.barc.gov.in/careers/recruitment.html",
      img_src : require("../../Screens/Job/img/jobLogo/barc.png"),
      alt:"Logo"
    },
    {
      id: "25",
      Title: "UI/UX Designer",
      Company: "yulu",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-4",
      WorkType: "Full Time",
      Link:"https://ats.careers.yulu.bike/#!/job-view/ui-ux-designer-bangalore-2022052216532727",
      img_src : require("../../Screens/Job/img/jobLogo/yulu.png"),
      alt:"Logo"
    },
    {
      id: "26",
      Title: "Business Analyst",
      Company: "Pharmeasy",
      Location: "Mumbai, Bangalore, Hyderabad, Pune, Delhi",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-6",
      WorkType: "Full Time",
      Link:" https://pharmeasy.in/careers/jobs/?src%3Dcareers%26p%3DeyJwYWdlVHlwZSI6ImpkIiwiY3ZTb3VyY2UiOiJjYXJlZXJzIiwicmVxSWQiOjE0MTUsInJlcXVlc3RlciI6eyJpZCI6IiIsImNvZGUiOiIiLCJuYW1lIjoiIn0sInBhZ2UiOiJjYXJlZXJzIiwiYnVmaWx0ZXIiOi0xLCJjdXN0b21GaWVsZHMiOnt9fQ==",
      img_src : require("../../Screens/Job/img/jobLogo/pharmeasy.jpg"),
      alt:"Logo"
    },
    {
      id: "27",
      Title: "Software Development Engineer-2",
      Company: "Masai School",
      Location: "Remote",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "3+",
      WorkType: "Full Time",
      Link:"https://angel.co/company/masai-school/jobs/2372658-software-development-engineer-2-remote-or-onsite",
      img_src : require("../../Screens/Job/img/jobLogo/masai.png"),
      alt:"Logo"
    },
    {
      id: "28",
      Title: "Assistant Professors(Department of English)",
      Company: "Jamia Millia Islamia",
      Location: "Remote, India",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "3-5",
      WorkType: "Full Time",
      Link:"https://www.jmi.ac.in/upload/advertisement/jobs_advt3_2022august6.pdf",
      img_src : require("../../Screens/Job/img/jobLogo/jamia.jpg"),
      alt:"Logo"
    },
    {
      id: "29",
      Title: "Development Manager Group",
      Company: "SbiLife",
      Location: "Pan india",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1",
      WorkType: "Full Time",
      Link:"https://www.sbilife.co.in/careers_sbilife",
      img_src : require("../../Screens/Job/img/jobLogo/sbilife.png"),
      alt:"Logo"
    },  
    {
      id: "30",
      Title: "Product Manager",
      Company: "magicpin",
      Location: "Remote",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-4",
      WorkType: "Full Time",
      Link:"https://magicpin.darwinbox.in/ms/candidate/careers/a62fb96044f785",
      img_src : require("../../Screens/Job/img/jobLogo/magicpin.png"),
      alt:"Logo"
    },
    {
      id: "31",
      Title: "Product Manager",
      Company: "chqbook",
      Location: "Remote",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2+",
      WorkType: "Full Time",
      Link:"https://chqbook.hire.trakstar.com/jobs/fk0qaqe/",
      img_src : require("../../Screens/Job/img/jobLogo/chqbook.png"),
      alt:"Logo"
    },
    
    {
      id: "36",
      Title: "Business Associate",
      Company: "Porter",
      Location: "Ludhiana, Punjab",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2-4",
      WorkType: "Full Time",
      Link:"https://porter.darwinbox.in/ms/candidate/careers/a6311f45d0b9bd",
      img_src : require("../../Screens/Job/img/jobLogo/porter.png"),
      alt:"Logo"
    },
    {
      id: "37",
      Title: "Signal processing algorithm developer",
      Company: "skyroot",
      Location: "Hyderabad",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://skyroot.in/career",
      img_src : require("../../Screens/Job/img/jobLogo/skyroot.png"),
      alt:"Logo"
    },
    {
      id: "38",
      Title: "Software Engineer",
      Company: "Open",
      Location: "Bangalore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "3",
      WorkType: "Full Time",
      Link:"https://jobs.lever.co/bankopen/29e77815-b846-42a2-96d7-339296414148",
      img_src : require("../../Screens/Job/img/jobLogo/open.png"),
      alt:"Logo"
    },
    {
      id: "39",
      Title: "Social Media Marketing Intern",
      Company: "Plum",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-2",
      WorkType: "Full Time",
      Link:"https://jobs.lever.co/plum/557d2c95-b235-498a-ac94-c42861dced6a",
      img_src : require("../../Screens/Job/img/jobLogo/plum.png"),
      alt:"Logo"
    },
    {
      id: "40",
      Title: "DFT Engineer",
      Company: "Nvidia",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-2",
      WorkType: "Full Time",
      Link:"https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/details/DFT-Engineer---Hardware_JR1961351?locationHierarchy1=2fcb99c455831013ea52b82135ba3266",
      img_src : require("../../Screens/Job/img/jobLogo/nvidia.png"),
      alt:"Logo"
    },
    {
      id: "41",
      Title: "Service Associate-HR",
      Company: "IBM",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "NOn Govt.",
      Experience: "1",
      WorkType: "Part Time",
      Link:"https://careers.ibm.com/job/15825530/service-associate-hr-bangalore-in/?codes=IBM_CareerWebSite",
      img_src : require("../../Screens/Job/img/jobLogo/ibm.png"),
      alt:"Logo"
    },
    {
      id: "42",
      Title: "HR",
      Company: "Axis Bank",
      Location: "Remote",
      Date: "Not Available",
      Type: "WFH",
      Experience: "1",
      WorkType: "Full Time",
      Link:"https://axisbank.ripplehire.com/candidate/?token=WIXhCuz0XRZ7H0GZCwjJ&source=CAREERSITE#detail/job/109442",
      img_src : require("../../Screens/Job/img/jobLogo/axisbank.png"),
      alt:"Logo"
    },
    {
      id: "43",
      Title: "Executive Director's Office",
      Company: "Wildlife trust of india",
      Location: "Noida ",
      Date: "Not Available",
      Type: "Govt.",
      Experience: "0-2",
      WorkType: "Full Time",
      Link:"https://jobs.wti.org.in/JobDetails?id=6305d06e798b875ddce9ae95",
      img_src : require("../../Screens/Job/img/jobLogo/wildlife.png"),
      alt:"Logo"
    },
    
    {
      id: "44",
      Title: "Java Developer",
      Company: "Quess",
      Location: "Hyderabad",
      Date: "Not Available",
      Type: "",
      Experience: "1",
      WorkType: "Full Time",
      Link:"https://talentflow.in/Search/Jobs/?61479-Java-Developer#.Yxb8QnZBzDc",
      img_src : require("../../Screens/Job/img/jobLogo/quess.png"),
      alt:"Logo"
    },
    {
      id: "45",
      Title: "SENIOR CUSTOMER SERVICE REPRESENTATIVE",
      Company: "HCL",
      Location: "Gurgaon",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link:"https://www.hcltech.com/jobs/associate-bfs",
      img_src : require("../../Screens/Job/img/jobLogo/hcl.png"),
      alt:"Logo"
    },
    {
      id: "46",
      Title: "ASSOCIATE- BFS",
      Company: "HCL",
      Location: "Noida",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link:"https://www.hcltech.com/jobs/associate-bfs",
      img_src : require("../../Screens/Job/img/jobLogo/hcl.png"),
      alt:"Logo"
    },
    {
      id: "47",
      Title: "Junior Operator",
      Company: "Cipla",
      Location: "Sikkim ",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://career10.successfactors.com/career?company=C0001172882P&career%5fns=job%5flisting%5fsummary&navBarLevel=JOB%5fSEARCH&_s.crb=1LlVkkou6tQituJOJjE%2fhcep%2fFuLAxQSrUT8CwAJHh4%3d",
      img_src : require("../../Screens/Job/img/jobLogo/cipla.jpg"),
      alt:"Logo"
    },
    {
      id: "48",
      Title: "HR",
      Company: "HR India",
      Location: "Delhi",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://www.humanresourceindia.com/job/hr-recruiter/",
      img_src : require("../../Screens/Job/img/jobLogo/hr.png"),
      alt:"Logo"
    },
    {
      id: "49",
      Title: "Technical Account Manager",
      Company: "Amazon",
      Location: "Singapore",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "0-2",
      WorkType: "Full Time",
      Link:"https://amazon.jobs/en/jobs/2238752/technical-account-manager-mandarin-speaker",
      img_src : require("../../Screens/Job/img/jobLogo/amazon.png"),
      alt:"Logo"
    },
    {
      id: "50",
      Title: "PGT Teacher",
      Company: "Government of Jharkhand",
      Location: "Jharkhand",
      Date: "Not Available",
      Type: "Govt.",
      // Experience: "2",
      WorkType: "Full Time",
      Link:"https://jssc.nic.in/notices/advertisement-pgttce-2022-regular-vacancy",
      img_src : require("../../Screens/Job/img/jobLogo/jharkhand.png"),
      alt:"Logo"
    },
    {
      id: "51",
      Title: "Graphics Compiler Automation Engineer(Full Stack)",
      Company: "Qualcomm",
      Location: "Hyderabad",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-3",
      WorkType: "Full Time",
      Link:"https://qualcomm.wd5.myworkdayjobs.com/en-US/External/job/Hyderabad-IND/Graphics-Compiler-Test-Engineer_3038963",
      img_src : require("../../Screens/Job/img/jobLogo/qualcomm.png"),
      alt:"Logo"
    },
    {
      id: "52",
      Title: "Product Application Engineer",
      Company: "AMD",
      Location: "Hyderabad,Telangana",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://jobs.amd.com/job/Hyderabad-Product-Application-Engineer-2%28202%29-Tela/931243900/",
      img_src : require("../../Screens/Job/img/jobLogo/amd.png"),
      alt:"Logo"
    },
    {
      id: "53",
      Title: "SMTS Software System Design Engineer",
      Company: "AMD",
      Location: "Bangalore, Karnataka",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://jobs.amd.com/job/Bangalore-SMTS-Software-System-Design-Eng_%28181121%29-Karn/929921200/",
      img_src : require("../../Screens/Job/img/jobLogo/amd.png"),
      alt:"Logo"
    },
    {
      id: "54",
      Title: "Staff Technical Writer",
      Company: "AMD",
      Location: "Hyderabad,Telangana",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "`-2",
      WorkType: "Full Time",
      Link:"https://jobs.amd.com/job/Hyderabad-Staff-Technical-Writer-Tela/894617400/",
      img_src : require("../../Screens/Job/img/jobLogo/amd.png"),
      alt:"Logo"
    },
    {
      id: "55",
      Title: "Software Engineer 2",
      Company: "INTUIT",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2+",
      WorkType: "Full Time",
      Link:"http://jobs.intuit.com/job/bengaluru/software-engineer-2/27595/36170913056?utm_source=copy&utm_medium=social_post&utm_campaign=Intuit_social",
      img_src : require("../../Screens/Job/img/jobLogo/intuit.png"),
      alt:"Logo"
    },
    {
      id: "56",
      Title: "Software Engineer 2- Full Stack",
      Company: "INTUIT",
      Location: "Bengaluru",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2+",
      WorkType: "Full Time",
      Link:"http://jobs.intuit.com/job/bengaluru/software-engineer-2-full-stack/27595/36078478784?utm_source=copy&utm_medium=social_post&utm_campaign=Intuit_social",
      img_src : require("../../Screens/Job/img/jobLogo/intuit.png"),
      alt:"Logo"
    },
    {
      id: "57",
      Title: "Software Engineer",
      Company: "Paypal",
      Location: "Chennai,Tamil Nadu",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "1-2",
      WorkType: "Full Time",
      Link:"https://wd1.myworkdaysite.com/recruiting/paypal/jobs/job/Chennai-Tamil-Nadu-India/Software-Engineer-3_R0093245?src=Eightfold",
      img_src : require("../../Screens/Job/img/jobLogo/paypal.jpg"),
      alt:"Logo"
    },
    {
      id: "58",
      Title: "Executive-Inside Sales",
      Company: "ADP",
      Location: "Delhi",
      Date: "Not Available",
      Type: "Non Govt.",
      Experience: "2",
      WorkType: "Full Time",
      Link:"https://jobs.adp.com/job/16631664/executive-inside-sales-chennai-in/#",
      img_src : require("../../Screens/Job/img/jobLogo/adp.png"),
      alt:"Logo"
    },
  ]
}
export default Jobdata;