const Internshipdata = {
        InternshipData:[
    {
      id: "0",
      Title: "Smart Manufacturing using CNC Router",
      Company: "Aicte Idea Lab - Guru Nanak Institutions Technical Campus",
      Location: "WFH",
      Date: "23-09-2022",
      Stipend: "Unpaid",
      WorkType: "Part Time",
      Link:"https://internship.aicte-india.org/internship-details.php?uid=INTERNSHIP_16632020596322730b435de",
      img_src : require("../../Screens/Internship/img/internlogo/gnitc.png"),
      alt:"Logo"
    },
    {
      id: "1",
      Title: "Web Development",
      Company: "Zed Age Infotech",
      Location: "Suri",
      Date: "31-10-2022",
      Stipend: "Unpaid",
      WorkType: "Part Time",
      Link:"https://www.zedageinfotech.co.in/recruitment.php",
      img_src : require("../../Screens/Internship/img/internlogo/zedage.png"),
      alt:"Logo"
    },
    {
      id: "2",
      Title: "Documentation Assistant",
      Company: "DTDC Express Ltd.",
      Location: "Pan India",
      Date: "Not Available",
      Stipend: "Unpaid",
      WorkType: "Part Time",
      Link:"https://www.apprenticeshipindia.gov.in/apprenticeship/opportunity-view/5cc2e2f5af11374ab473b582",
      img_src : require("../../Screens/Internship/img/internlogo/dtdc.png"),
      alt:"Logo"
    },
    {
      id: "3",
      Title: "Quality Analyst Intern",
      Company: "Adobe",
      Location: "Bangalore",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/Non-Tech-Intern-BS_R123584?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "4",
      Title: "C++ Developer",
      Company: "Adobe",
      Location: "Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/Tech-Intern-BS_R129379?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "4",
      Title: "C++ Developer",
      Company: "Adobe",
      Location: "Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/SheSparks---C---Developer_R129386?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "5",
      Title: "Business Consultant",
      Company: "Adobe",
      Location: "Bangalore,Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/SheSparks---Business-Consultant_R129183?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "6",
      Title: "Solution Architect",
      Company: "Adobe",
      Location: "Bangalore,Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/Non-Tech-Intern-BS_R129182?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "7",
      Title: "AEM Intern",
      Company: "Adobe",
      Location: "Bangalore,Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/details/Non-Tech-Intern-BS_R129181?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e&workerSubType=3ba4ecdf4893100b2f8d08d56d8d6c8e",
      img_src : require("../../Screens/Internship/img/internlogo/adobe.png"),
      alt:"Logo"
    },
    {
      id: "8",
      Title: "Software Engineering Intern",
      Company: "Google",
      Location: "Bangalore",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.google.com/jobs/results/80503484702433990-software-engineering-intern-summer-2023/?distance=50&employment_type=INTERN&location=India&q=",
      img_src : require("../../Screens/Internship/img/internlogo/google.png"),
      alt:"Logo"
    },
    {
      id: "9",
      Title: "Intern (Technical-Engineering)",
      Company: "Synopsys",
      Location: "Noida",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25235&siteid=5359&PageType=JobDetails&jobid=1970413#jobDetails=1970413_5359",
      img_src : require("../../Screens/Internship/img/internlogo/synopsys.png"),
      alt:"Logo"
    },
    {
      id: "10",
      Title: "Intern (Technical-Engineering)",
      Company: "Synopsys",
      Location: "Bangalore",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25235&siteid=5359&PageType=JobDetails&jobid=1971081",
      img_src : require("../../Screens/Internship/img/internlogo/synopsys.png"),
      alt:"Logo"
    },
    {
      id: "11",
      Title: "Intern (Technical-Engineering)",
      Company: "Synopsys",
      Location: "Hyderabad",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25235&siteid=5359&PageType=JobDetails&jobid=1970899#jobDetails=1970899_5359",
      img_src : require("../../Screens/Internship/img/internlogo/synopsys.png"),
      alt:"Logo"
    },
    {
      id: "12",
      Title: "Software Engineering",
      Company: "Microsoft",
      Location: "US",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.microsoft.com/us/en/job/1370686/Software-Engineering-PhD-Intern-Opportunities",
      img_src : require("../../Screens/Internship/img/internlogo/microsoft.png"),
      alt:"Logo"
    },
    {
      id: "13",
      Title: "Software Engineering",
      Company: "Microsoft",
      Location: "Paris, France",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.microsoft.com/us/en/job/1464936/Software-Engineering-Internship-Opportunities-France-Start-date-Feb-March-2023",
      img_src : require("../../Screens/Internship/img/internlogo/microsoft.png"),
      alt:"Logo"
    },
    {
      id: "14",
      Title: "Web Developer Intern",
      Company: "Dechcept Private Limited",
      Location: "Surat",
      Date: "Not Available",
      Stipend: "2000",
      WorkType: "Full Time",
      Link:"https://www.dechcept.com/careers/728fc8d0-24b9-11eb-a57a-ef4805be3fd8",
      img_src : require("../../Screens/Internship/img/internlogo/dechcept.png"),
      alt:"Logo"
    },
    {
      id: "15",
      Title: "Software Fresher Interns",
      Company: "Mobzway Technologies LLP",
      Location: "Remote",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.mobzway.com/jobs/Careers/453693000005184008/Software-Fres",
      img_src : require("../../Screens/Internship/img/internlogo/mobzway.png"),
      alt:"Logo"
    },
    {
      id: "16",
      Title: "Web Developer",
      Company: "Sypree",
      Location: "Mumbai",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://syspree.com/career/web-developer-2/",
      img_src : require("../../Screens/Internship/img/internlogo/syspree.png"),
      alt:"Logo"
    },
    {
      id: "17",
      Title: "Web Developer",
      Company: "medOne",
      Location: "Paris, France",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://www.moplindia.com/medOneWeb/Career",
      img_src : require("../../Screens/Internship/img/internlogo/medOne.png"),
      alt:"Logo"
    },
    {
      id: "18",
      Title: "Software Engineer",
      Company: "Ciena",
      Location: "Gurugram",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://ciena.wd5.myworkdayjobs.com/en-US/Careers/job/Gurugram/Software-Engineer-Intern_R020719",
      img_src : require("../../Screens/Internship/img/internlogo/ciena.png"),
      alt:"Logo"
    },
    {
      id: "19",
      Title: "Software Engineer",
      Company: "Ciena",
      Location: "Gurugram",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://ciena.wd5.myworkdayjobs.com/en-US/Careers/job/Gurugram/Software-Intern_R019083",
      img_src : require("../../Screens/Internship/img/internlogo/ciena.png"),
      alt:"Logo"
    },
    {
      id: "20",
      Title: "Web Development",
      Company: "Dynamisers Solutions Pvt. Ltd.",
      Location: "Gurugram",
      Date: "Not Available",
      Stipend: "2000-5000",
      WorkType: "Full Time",
      Link:"https://www.dynamisers.com/internship-website-development.php",
      img_src : require("../../Screens/Internship/img/internlogo/dynamisers.png"),
      alt:"Logo"
    },
    {
      id: "21",
      Title: "Software Developer",
      Company: "IBM",
      Location: "Gurugram",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.ibm.com/job/16757007/intern-software-developer-kochi-in/?codes=JB_Indeed",
      img_src : require("../../Screens/Internship/img/internlogo/ibm.png"),
      alt:"Logo"
    },
    {
      id: "22",
      Title: "Content Writing",
      Company: "FirstView",
      Location: "Remote",
      Date: "Not Available",
      Stipend: "8000",
      WorkType: "Full Time",
      Link:"https://careers.firstviewgroup.com/jobs/Careers/572062000001943177/Internship---Content-writing?source=CareerSite",
      img_src : require("../../Screens/Internship/img/internlogo/firstview.png"),
      alt:"Logo"
    },
    {
      id: "23",
      Title: "Software - Frontend",
      Company: "Leegality",
      Location: "Remote",
      Date: "Not Available",
      Stipend: "25000",
      WorkType: "Full Time",
      Link:"https://careers.leegality.com/jobs/Careers/10926000023353005/Software-Intern---Frontend?source=CareerSite",
      img_src : require("../../Screens/Internship/img/internlogo/leegality.png"),
      alt:"Logo"
    },
    {
      id: "24",
      Title: "Software - Python",
      Company: "Leegality",
      Location: "Remote",
      Date: "Not Available",
      Stipend: "25000",
      WorkType: "Full Time",
      Link:"https://careers.leegality.com/jobs/Careers/10926000023775285/Software-Intern---Python?source=CareerSite",
      img_src : require("../../Screens/Internship/img/internlogo/leegality.png"),
      alt:"Logo"
    },
    {
      id: "25",
      Title: "Web Development",
      Company: "Maniten",
      Location: "Gurugram",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://maniten.in/career/",
      img_src : require("../../Screens/Internship/img/internlogo/maniten.png"),
      alt:"Logo"
    },
    {
      id: "26",
      Title: "Digital Marketing",
      Company: "dar2gear",
      Location: "Noida",
      Date: "Not Available",
      Stipend: "5000-7000",
      WorkType: "Full Time",
      Link:"https://dare2gear.com/careers/digital-marketing-intern/",
      img_src : require("../../Screens/Internship/img/internlogo/dare2gear.png"),
      alt:"Logo"
    },
    {
      id: "27",
      Title: "Digital Marketing",
      Company: "Oodles Technologies",
      Location: "Haryana",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://careers.oodles.io/jobs/720",
      img_src : require("../../Screens/Internship/img/internlogo/oodles.png"),
      alt:"Logo"
    },
    {
      id: "28",
      Title: "Software Developer",
      Company: "Urjasoft Enterprises Pvt. Ltd",
      Location: "",
      Date: "Not Available",
      Stipend: "Paid",
      WorkType: "Full Time",
      Link:"https://urjasoft.com/job-apply",
      img_src : require("../../Screens/Internship/img/internlogo/urjasoft.png"),
      alt:"Logo"
    },
  ]
};
export default Internshipdata;